spring:
  mail:
    host: smtp.gmail.com
    username: insidesy4@gmail.com
    port: '587'
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
    password: exndsdqrduundgoc
  application:
    name: javafeed
  servlet:
    multipart:
      max-file-size: '-1'
      max-request-size: '-1'
  jpa:
    properties:
      hibernate:
        use_sql_comments: 'true'
        format_sql: 'true'
        show_sql: 'true'
    hibernate:
      ddl-auto: update
  datasource:
    password: ${DB_PASSWORD}
    username: ${DB_USERNAME}
    url: jdbc:mysql://${DB_HOST}:3306/javafeed_testdb

jwt:
  secret:
    key: ${JWT_KEY}

cloud:
  aws:
    credentials:
      secret-key: ${SECRET_KEY}
      access-key: ${ACCESS_KEY}
    s3:
      bucketName: ${BUCKET_NAME}
    region:
      static: ap-northeast-2
    stack:
      auto: 'false'
